#version 430 core

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer OutputValues {
    uint outputValues[];
};

layout(std430, binding = 1) readonly buffer BlockOffsets {
    uint blockOffsets[];
};

uniform int uElementCount;

void main() {
#if LAB_CHECKPOINT >= 3
    uint index = gl_GlobalInvocationID.x;
    if (index >= uint(uElementCount)) {
        return;
    }
    outputValues[index] += blockOffsets[index / 512u];
#else
    if (uElementCount < 0) {
        outputValues[0] = blockOffsets[0];
    }
#endif
}
