export function courseCmake(project, { hasSnapshotShaders = false } = {}) {
  const projectNumber = Number(project.id);
  const shaderSetup = hasSnapshotShaders
    ? `
    # Shader thay đổi theo checkpoint được chạy trực tiếp từ source để hỗ trợ hot reload.
    target_compile_definitions(\${name} PRIVATE
        COURSE_SHADER_DIRECTORY="\${CMAKE_CURRENT_SOURCE_DIR}/\${source_directory}/shaders"
    )
    add_custom_command(TARGET \${name} POST_BUILD
        COMMAND \${CMAKE_COMMAND} -E copy_directory
            "\${CMAKE_CURRENT_SOURCE_DIR}/\${source_directory}/shaders"
            "$<TARGET_FILE_DIR:\${name}>/shaders"
    )
`
    : "";
  return `# Generated from scripts/course-cmake.mjs. Do not edit this file directly.
cmake_minimum_required(VERSION 3.24)
project(project_${projectNumber} LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

option(COURSE_USE_INSTALLED_SDL3 "Use an exact SDL 3.4.8 package supplied by CI" OFF)
if(COURSE_USE_INSTALLED_SDL3)
    find_package(SDL3 3.4.8 EXACT CONFIG REQUIRED)
else()
    include(FetchContent)
    # Khóa SDL ở đúng release và checksum để mọi máy dùng cùng source.
    set(SDL_TESTS OFF CACHE BOOL "" FORCE)
    set(SDL_EXAMPLES OFF CACHE BOOL "" FORCE)
    set(SDL_INSTALL OFF CACHE BOOL "" FORCE)
    FetchContent_Declare(SDL3
        URL https://github.com/libsdl-org/SDL/releases/download/release-3.4.8/SDL3-3.4.8.tar.gz
        URL_HASH SHA256=e9fff7467fb60f037e6708da18b25560649e4c63edc2a69bb871b960d9cbfbba
    )
    FetchContent_MakeAvailable(SDL3)
endif()

option(BUILD_CHECKPOINTS "Build starter and lesson checkpoints" OFF)
set(PROJECT_CHECKPOINT_COUNT ${project.checkpointCount})

# Dùng cùng mức warning cho final, starter, checkpoint và tests.
function(enable_course_warnings target)
    if(MSVC)
        target_compile_options(\${target} PRIVATE /W4 /permissive-)
    else()
        target_compile_options(\${target} PRIVATE -Wall -Wextra -Wpedantic)
    endif()
endfunction()

# Mỗi target biên dịch toàn bộ translation unit trong src của snapshot tương ứng.
function(add_lab_app name source_directory)
    file(GLOB_RECURSE lab_sources CONFIGURE_DEPENDS
        "\${CMAKE_CURRENT_SOURCE_DIR}/\${source_directory}/src/*.cc"
        "\${CMAKE_CURRENT_SOURCE_DIR}/\${source_directory}/src/*.cpp"
        "\${CMAKE_CURRENT_SOURCE_DIR}/\${source_directory}/src/*.cxx"
    )
    if(NOT lab_sources)
        message(FATAL_ERROR "\${source_directory}/src must contain at least one C++ source file")
    endif()
    add_executable(\${name} \${lab_sources})
    target_include_directories(\${name} PRIVATE \${source_directory}/include)
    target_link_libraries(\${name} PRIVATE SDL3::SDL3)
    # Windows tìm DLL cạnh executable; áp dụng cả FetchContent lẫn package đã cài.
    if(WIN32 AND TARGET SDL3::SDL3-shared)
        add_custom_command(TARGET \${name} POST_BUILD
            COMMAND \${CMAKE_COMMAND} -E copy_if_different
                "$<TARGET_FILE:SDL3::SDL3-shared>"
                "$<TARGET_FILE_DIR:\${name}>"
            VERBATIM
        )
    endif()
    if(EXISTS "\${CMAKE_CURRENT_SOURCE_DIR}/assets")
        add_custom_command(TARGET \${name} POST_BUILD
            COMMAND \${CMAKE_COMMAND} -E copy_directory
                "\${CMAKE_CURRENT_SOURCE_DIR}/assets"
                "$<TARGET_FILE_DIR:\${name}>/assets"
        )
    endif()
${shaderSetup}    enable_course_warnings(\${name})
endfunction()

add_lab_app(project_${projectNumber}_final final)
if(BUILD_CHECKPOINTS)
    add_lab_app(project_${projectNumber}_starter starter)
    foreach(step RANGE 1 \${PROJECT_CHECKPOINT_COUNT})
        if(step LESS 10)
            set(step_directory "0\${step}")
        else()
            set(step_directory "\${step}")
        endif()
        add_lab_app(project_${projectNumber}_checkpoint_\${step} checkpoints/\${step_directory})
    endforeach()
endif()

# Tests chỉ include code thuần trong final/include và không cần mở SDL window.
include(CTest)
if(BUILD_TESTING)
    file(GLOB_RECURSE test_sources CONFIGURE_DEPENDS "\${CMAKE_CURRENT_SOURCE_DIR}/tests/*.cpp")
    add_executable(project_${projectNumber}_tests \${test_sources})
    target_include_directories(project_${projectNumber}_tests PRIVATE final/include)
    enable_course_warnings(project_${projectNumber}_tests)
    add_test(NAME project_${projectNumber}_validation COMMAND project_${projectNumber}_tests)
endif()
`;
}
